### ISSUE TITLE
How to Develop Other Payment Gateway and Shipping?

### ISSUE THREAD

**Issue by nakamuraagatha** [tryshoppe/shoppe-example#10]
How to Develop Other Payment Gateway and Shipping?, any sample blank extensions format?

**Comment by deanperry** [comment]
Apologies for the delay in replying, I've just seen this. You can look at the shoppe-stripe gem to see how that works and integrates with both Stripe & Shoppe - https://github.com/tryshoppe/shoppe-stripe
