### ISSUE TITLE
$ rails generate shoppe:setup $ rails generate nifty:key_value_store:migration

### ISSUE THREAD

**Issue by andreavecy** [tryshoppe/shoppe-example#11]
rails generate
/home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
/home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- net/ssh (LoadError)
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/fog-1.31.0/lib/fog/joyent/compute.rb:3:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/fog-1.31.0/lib/fog/joyent.rb:1:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/fog-1.31.0/lib/fog.rb:41:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:3:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:9:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/carrierwave-0.10.0/lib/carrierwave.rb:78:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/shoppe-1.1.1/lib/shoppe.rb:14:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `each'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:134:in `require'
	from /home/andreavecino/Documentos/ROR/project/config/application.rb:7:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/railties-4.0.2/lib/rails/commands.rb:43:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.2.1/gems/railties-4.0.2/lib/rails/commands.rb:43:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by deanperry** [comment]
Have you followed the docs? http://tryshoppe.com/docs/tutorials/setting-up





On Tue, Nov 24, 2015 at 5:38 AM -0800, "Andrea Vecino" <notifications@github.com> wrote:












Reopened #11.

**Comment by andreavecy** [comment]
yes, when i write the step: 
$ rails generate shoppe:setup

**Comment by deanperry** [comment]
What version of Rails and Ruby are you using?

**Comment by andreavecy** [comment]
rails 4.2.5
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by andreavecy** [comment]
rvm rubies

   ruby-1.9.2-p330 [ x86_64 ]
   ruby-2.0.0-p643 [ x86_64 ]
   ruby-2.1.4 [ x86_64 ]
=> ruby-2.2.1 [ x86_64 ]

**Comment by deanperry** [comment]
You can try- reinstalling the gem- using bundle exec rails generate
- using the GitHub version of the gem
